name: build RPM

on:
  push:
    branches:
      - main
  workflow_dispatch:
  release:
    types: [published]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          sudo apt-get install -y alien
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build RPM
        run: |
          python3 getrelease.py
          # set the filename to env variable
          export RPM_FILE=$(ls *.rpm)
          

      - name: Upload RPM
        uses: actions/upload-artifact@v3
        with:
          path: ./*.rpm

      - name: Release RPM
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in ./*.rpm; do
            gh release upload ${{ github.event.release.tag_name }} $file
          done

